services:
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - my-pg-network
networks:
  my-pg-network:
    driver: bridge
