version: "3.8"
services:
  nginx:
    image: nginx:alpine
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    deploy:
      mode: global
    networks:
      - mynet
  postgres:
    image: postgres:17-alpine
    networks:
      - mynet
    deploy:
      placement:
        constraints:
          - "node.labels.postgres==true"
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  mynet:
    driver: overlay
volumes:
  pgdata:
configs:
  nginx_conf:
    file: ./nginx/nginx.conf
